version: "3.9"
services:
  component:
    build: .
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  db:
    image: "mariadb:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: article
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin123
    ports:
      - "3333:80"