server:
  port: 42069

spring:
  application:
    name: shop

feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscovery:8761/eureka}
#    enabled: false


#apigateway:
#  url: http://localhost:8080